export const MOCK_RECIPES = [
  {
    id: -1,
    title: 'Cá Hồi Áp Chảo Sốt Bơ Tỏi',
    description: 'Món cá hồi áp chảo mềm ngọt, kết hợp cùng sốt bơ tỏi thơm lừng, rất thích hợp cho bữa tối dinh dưỡng.',
    ingredients: '2 lát cá hồi tươi\n2 muỗng canh bơ lạt\n3 tép tỏi băm\n1 muỗng canh nước cốt chanh\nMuối, tiêu, lá mùi tây',
    instructions: '1. Rửa sạch cá, thấm khô, ướp với muối tiêu.\n2. Áp chảo cá mỗi mặt 3-4 phút đến khi vàng đều.\n3. Trong cùng chảo, đun chảy bơ, phi thơm tỏi, thêm nước cốt chanh.\n4. Rưới sốt lên cá và rắc mùi tây.',
    difficulty: 'Dễ',
    cooking_time: 20,
    servings: 2,
    image_url: 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=800&auto=format&fit=crop',
    category_name: 'Eat Clean',
    author_name: 'Chef Minh',
    views: 1205,
    created_at: new Date().toISOString(),
  },
  {
    id: -2,
    title: 'Salad Ức Gà Nướng Mật Ong',
    description: 'Món salad thanh mát với ức gà nướng đậm đà, lý tưởng cho thực đơn Eat Clean hoặc giảm cân.',
    ingredients: '200g ức gà\n1 cây xà lách romaine\nCà chua bi, dưa leo\n2 muỗng canh mật ong\n1 muỗng canh nước tương\nDầu oliu, giấm táo',
    instructions: '1. Ướp gà với mật ong, nước tương, chút muối trong 15 phút.\n2. Nướng hoặc áp chảo gà đến khi chín vàng, thái lát.\n3. Trộn các loại rau củ với sốt dầu giấm.\n4. Đặt gà lên trên và thưởng thức.',
    difficulty: 'Dễ',
    cooking_time: 25,
    servings: 1,
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop',
    category_name: 'Món Salad',
    author_name: 'Healthy Ly',
    views: 890,
    created_at: new Date().toISOString(),
  },
  {
    id: -3,
    title: 'Bò Lúc Lắc Khoai Tây Chiên',
    description: 'Món bò lúc lắc kiểu Việt Nam với thịt bò mềm tan, kết hợp khoai tây chiên giòn rụm.',
    ingredients: '300g thịt thăn bò\n1/2 củ hành tây\n1/2 quả ớt chuông\n2 củ khoai tây\nNước tương, dầu hào, tiêu, tỏi',
    instructions: '1. Thái bò vuông cờ, ướp tỏi, nước tương, dầu hào.\n2. Khoai tây thái múi cau, chiên giòn.\n3. Xào hành tây, ớt chuông vừa chín tới, trút ra đĩa.\n4. Xào bò lửa lớn thật nhanh, trộn đều với rau củ.',
    difficulty: 'Trung bình',
    cooking_time: 30,
    servings: 2,
    image_url: 'https://images.unsplash.com/photo-1544378730-8b5d03ba6d14?w=800&auto=format&fit=crop',
    category_name: 'Bữa Tối',
    author_name: 'Bếp Mẹ Bon',
    views: 3421,
    created_at: new Date().toISOString(),
  },
  {
    id: -4,
    title: 'Canh Rong Biển Nấu Đậu Hũ',
    description: 'Món canh thanh mát, giải nhiệt, nấu cực kỳ nhanh gọn cho những ngày bận rộn.',
    ingredients: '20g rong biển khô\n1 miếng đậu hũ non\n100g thịt băm (hoặc nấm cho món chay)\nHành lá, hạt nêm, dầu mè',
    instructions: '1. Ngâm rong biển cho nở, xắt nhỏ.\n2. Đậu hũ thái hạt lựu.\n3. Xào sơ thịt băm, cho nước vào đun sôi.\n4. Thêm rong biển và đậu hũ, nêm nếm vừa ăn, nhỏ thêm dầu mè.',
    difficulty: 'Dễ',
    cooking_time: 15,
    servings: 3,
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&auto=format&fit=crop',
    category_name: 'Súp & Canh',
    author_name: 'Ngọc Lan',
    views: 1500,
    created_at: new Date().toISOString(),
  },
  {
    id: -5,
    title: 'Mì Ý Sốt Cà Chua Thịt Băm',
    description: 'Spaghetti sốt Bolognese truyền thống, dễ làm và luôn được các bé yêu thích.',
    ingredients: '200g mì Ý\n200g thịt bò băm\n3 quả cà chua chín\n1/2 củ hành tây\nTỏi, lá oregano, dầu oliu',
    instructions: '1. Luộc mì Ý chín tới, vớt ra trộn chút dầu oliu.\n2. Làm sốt: phi thơm tỏi hành tây, cho bò băm vào xào.\n3. Thêm cà chua xay nhuyễn, đun sệt, nêm nếm gia vị và oregano.\n4. Rưới sốt lên mì và rắc phô mai (tùy thích).',
    difficulty: 'Trung bình',
    cooking_time: 35,
    servings: 2,
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&auto=format&fit=crop',
    category_name: 'Bữa Tối',
    author_name: 'Chef Minh',
    views: 4520,
    created_at: new Date().toISOString(),
  },
  {
    id: -6,
    title: 'Cơm Chiên Dương Châu',
    description: 'Món cơm chiên đa sắc màu với lạp xưởng, tôm, trứng và rau củ, tận dụng cơm nguội hiệu quả.',
    ingredients: '2 chén cơm nguội\n1 cây lạp xưởng\n50g tôm sú\n1 quả trứng gà\nĐậu cô ve, cà rốt, hành lá',
    instructions: '1. Trứng đánh tan, chiên chín rồi xắt chỉ. Cà rốt, đậu xắt hạt lựu.\n2. Lạp xưởng, tôm thái nhỏ xào chín.\n3. Đảo tơi cơm nguội trên chảo nóng với chút dầu.\n4. Cho tất cả nguyên liệu vào đảo đều, nêm nếm vừa ăn.',
    difficulty: 'Dễ',
    cooking_time: 20,
    servings: 2,
    image_url: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop',
    category_name: 'Nhanh & Gọn',
    author_name: 'Anh Đầu Bếp',
    views: 2210,
    created_at: new Date().toISOString(),
  },
  {
    id: -7,
    title: 'Gà Hầm Sâm Hàn Quốc (Samgyetang)',
    description: 'Món ăn bổ dưỡng giúp phục hồi sức khỏe, gà hầm mềm rục cùng nhân sâm và táo đỏ.',
    ingredients: '1 con gà tre hoặc gà ác\n1 củ nhân sâm tươi\n5 quả táo đỏ, 3 hạt dẻ\n2 muỗng canh gạo nếp\nTỏi, hành lá',
    instructions: '1. Gạo nếp ngâm nở. Nhồi nếp, táo đỏ, hạt dẻ, sâm vào bụng gà.\n2. Khâu kín bụng gà lại.\n3. Cho gà vào nồi áp suất, đổ ngập nước, đun trong 45 phút.\n4. Rắc hành lá và dùng nóng với muối tiêu.',
    difficulty: 'Khó',
    cooking_time: 60,
    servings: 2,
    image_url: 'https://images.unsplash.com/photo-1585931668832-6a695dbbf77c?w=800&auto=format&fit=crop',
    category_name: 'Nồi Áp Suất',
    author_name: 'Hana Kitchen',
    views: 1100,
    created_at: new Date().toISOString(),
  },
  {
    id: -8,
    title: 'Đậu Hũ Tứ Xuyên Thuần Chay',
    description: 'Phiên bản thuần chay của món đậu hũ Tứ Xuyên nổi tiếng, cay nồng đậm vị.',
    ingredients: '2 miếng đậu hũ non\n100g nấm đùi gà băm nhỏ\n1 muỗng sa tế chay\nNước tương, tiêu sọ, gừng, tỏi',
    instructions: '1. Đậu hũ non chần qua nước sôi ngâm muối, vớt ra thái vuông.\n2. Phi thơm gừng tỏi, xào nấm đùi gà và sa tế.\n3. Thêm nước tương, chút nước, đun sôi nhẹ.\n4. Cho đậu hũ vào lắc nhẹ chảo, đun sệt rồi tắt bếp.',
    difficulty: 'Trung bình',
    cooking_time: 20,
    servings: 2,
    image_url: 'https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?w=800&auto=format&fit=crop',
    category_name: 'Thuần Chay',
    author_name: 'Vegan Life',
    views: 840,
    created_at: new Date().toISOString(),
  },
  {
    id: -9,
    title: 'Trứng Chiên Bọt Biển (Souffle Omelet)',
    description: 'Món trứng bồng bềnh như mây, siêu mềm mịn và đẹp mắt chỉ với 2 quả trứng.',
    ingredients: '2 quả trứng gà\n1/2 muỗng cà phê đường\nChút bơ lạt',
    instructions: '1. Tách riêng lòng đỏ và lòng trắng.\n2. Đánh lòng trắng với đường tới khi bông cứng.\n3. Trộn nhẹ nhàng lòng đỏ vào lòng trắng.\n4. Áp chảo với bơ lửa nhỏ, gập đôi lại khi mặt dưới xém vàng.',
    difficulty: 'Dễ',
    cooking_time: 10,
    servings: 1,
    image_url: 'https://images.unsplash.com/photo-1525640788966-69bdb028aa73?w=800&auto=format&fit=crop',
    category_name: 'Nhanh & Gọn',
    author_name: 'Bếp Cô Tấm',
    views: 3100,
    created_at: new Date().toISOString(),
  },
  {
    id: -10,
    title: 'Miến Trộn Hàn Quốc (Japchae)',
    description: 'Món miến dai dai trộn cùng thịt bò và đa dạng các loại rau củ giòn ngọt.',
    ingredients: '200g miến Hàn Quốc\n100g thịt bò\nCà rốt, nấm đông cô, cải bó xôi\nDầu mè, nước tương, vừng rang',
    instructions: '1. Luộc miến chín dai, trộn với dầu mè.\n2. Rau củ thái sợi xào chín từng loại.\n3. Thịt bò thái mỏng ướp gia vị, xào chín tới.\n4. Trộn tất cả cùng sốt tương ngọt, rắc vừng rang lên trên.',
    difficulty: 'Trung bình',
    cooking_time: 35,
    servings: 3,
    image_url: 'https://images.unsplash.com/photo-1583224964978-225ddb3ea354?w=800&auto=format&fit=crop',
    category_name: 'Thực đơn bận rộn',
    author_name: 'Kim Cook',
    views: 1800,
    created_at: new Date().toISOString(),
  }
];

export const MOCK_BLOG_POSTS = [
  {
    id: -1,
    title: '5 Bí Quyết Giữ Rau Củ Tươi Lâu Trong Tủ Lạnh',
    excerpt: 'Bạn thường vứt bỏ rau củ vì chúng héo quá nhanh? Thử ngay 5 mẹo nhỏ nhưng có võ này để giữ thực phẩm tươi cả tuần nhé.',
    content: '<p>Rau củ thường rất nhanh héo nếu không được bảo quản đúng cách. Dưới đây là 5 mẹo: 1. Sử dụng giấy thấm hút ẩm bọc rau củ trước khi cho vào túi màng bọc. 2. Không rửa rau nếu chưa sử dụng ngay. 3. Để riêng các loại quả sinh khí ethylene như táo, chuối. 4. Cắt bỏ bớt lá của các loại củ (cà rốt, củ cải) để tránh mất nước. 5. Tận dụng hộp bảo quản chân không.</p>',
    image_url: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800&auto=format&fit=crop',
    category_name: 'Mẹo Vặt',
    author_name: 'Bếp Trưởng',
    likes: 342,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    status: 'approved'
  },
  {
    id: -2,
    title: 'Review 3 Quán Phở Thìn Lò Đúc Gốc Tại Hà Nội',
    excerpt: 'Cùng mình dạo quanh các cơ sở Phở Thìn nổi tiếng để xem đâu mới là hương vị chuẩn nhất, đáng thử nhất.',
    content: '<p>Phở Thìn Lò Đúc nổi tiếng với cách thái thịt bò vụn, xào lăn ngập tỏi hành. Khi thử nghiệm 3 cơ sở khác nhau tại Hà Nội, tôi nhận thấy cơ sở gốc ở số 13 Lò Đúc vẫn giữ được hương vị nước dùng béo ngậy đặc trưng nhất, dù không gian có phần chật hẹp. Trong khi đó, các cơ sở nhượng quyền lại nhạt hơn một chút nhưng không gian thoải mái hơn.</p>',
    image_url: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cb438?w=800&auto=format&fit=crop',
    category_name: 'Review Nhà Hàng',
    author_name: 'Foodie Hà Thành',
    likes: 1024,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    status: 'approved'
  },
  {
    id: -3,
    title: 'Eat Clean Là Gì? Bắt Đầu Eat Clean Dễ Dàng Cho Người Mới',
    excerpt: 'Khái niệm Eat Clean đang rất phổ biến, nhưng bắt đầu như thế nào để không bị nản chí? Cùng tìm hiểu lộ trình 7 ngày đầu.',
    content: '<p>Eat clean (Ăn sạch) là chế độ ăn ưu tiên thực phẩm tươi, tự nhiên và hạn chế tối đa thực phẩm chế biến sẵn. Bắt đầu đơn giản bằng cách: đổi đường tinh luyện sang đường ăn kiêng/mật ong; đổi gạo trắng sang gạo lứt; bổ sung nhiều chất xơ hơn và hạn chế đồ chiên xào nhiều dầu mỡ. Quan trọng nhất là "lắng nghe cơ thể".</p>',
    image_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&auto=format&fit=crop',
    category_name: 'Dinh Dưỡng',
    author_name: 'Coach LyLy',
    likes: 560,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    status: 'approved'
  },
  {
    id: -4,
    title: 'Sự Thật Thú Vị Về Nước Mắm Truyền Thống Việt Nam',
    excerpt: 'Từ những con cá cơm tươi rói đến giọt nước mắm nhĩ màu hổ phách, đó là cả một nghệ thuật lên men độc đáo.',
    content: '<p>Nước mắm truyền thống Việt Nam được ủ chượp tự nhiên từ cá và muối theo tỷ lệ 3:1 trong các thùng gỗ lớn từ 12-24 tháng. Nước mắm chuẩn phải có độ đạm cao, mùi thơm đặc trưng không bị tanh, và khi nếm có vị mặn ngọt đậm đà đọng lại nơi cuống họng. Khác hẳn với nước mắm công nghiệp pha chế.</p>',
    image_url: 'https://images.unsplash.com/photo-1628191010210-a59de33e5941?w=800&auto=format&fit=crop',
    category_name: 'Văn Hóa Ẩm Thực',
    author_name: 'Nhà Nghiên Cứu',
    likes: 415,
    created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    status: 'approved'
  },
  {
    id: -5,
    title: 'Kỹ Thuật Thái Hạt Lựu (Brunoise) Chuẩn Đầu Bếp 5 Sao',
    excerpt: 'Học cách cầm dao và thái hạt lựu cực đều tay chỉ với vài bước thực hành cơ bản tại nhà.',
    content: '<p>Thái hạt lựu (Brunoise) là kỹ thuật cắt khối vuông nhỏ kích thước khoảng 2-3mm. Kỹ thuật: Bước 1 - Cắt nguyên liệu thành khối chữ nhật đều đặn (trimming). Bước 2 - Thái lát mỏng (Julienne). Bước 3 - Ghép các lát mỏng và thái thành hạt lựu đều tay. Lưu ý luôn giấu đầu ngón tay cái để tránh bị đứt tay (Claw grip).</p>',
    image_url: 'https://images.unsplash.com/photo-1556910103-1c02745a805f?w=800&auto=format&fit=crop',
    category_name: 'Kỹ Thuật Nấu',
    author_name: 'Chef Tuấn',
    likes: 290,
    created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
    status: 'approved'
  },
  {
    id: -6,
    title: 'Làm Sao Để Nấu Cơm Niêu Cháy Đáy Giòn Tan?',
    excerpt: 'Bí quyết căn lửa và thời gian để có được lớp cháy cơm vàng ươm, giòn rụm mà không bị khét lẹt.',
    content: '<p>Bí quyết nấu cơm niêu ngon nằm ở nồi đất và cách canh lửa. Gạo sau khi ngâm 30 phút cho vào nồi đun sôi. Khi cạn nước, phải vặn lửa thật nhỏ và xoay đều nồi để nhiệt phân bố khắp đáy. Có thể nhỏ thêm vài giọt dầu ăn hoặc mỡ heo men theo thành nồi để lớp cháy bong ra dễ dàng và giòn rụm hơn.</p>',
    image_url: 'https://images.unsplash.com/photo-1536622204620-22c6762332bc?w=800&auto=format&fit=crop',
    category_name: 'Kỹ Thuật Nấu',
    author_name: 'Bếp Quê',
    likes: 180,
    created_at: new Date(Date.now() - 86400000 * 18).toISOString(),
    status: 'approved'
  },
  {
    id: -7,
    title: 'Sai Lầm Khủng Khiếp Khi Sử Dụng Thớt Gỗ',
    excerpt: 'Rửa thớt bằng nước rửa chén thông thường có đủ sạch? Đọc ngay để biết cách vệ sinh thớt an toàn.',
    content: '<p>Nhiều người có thói quen thái thịt sống rồi rửa thớt qua loa để thái rau chín. Điều này gây nhiễm khuẩn chéo nghiêm trọng. Thớt gỗ cần được vệ sinh bằng giấm trắng hoặc chanh và muối hột để diệt khuẩn. Hơn nữa, thớt gỗ không nên ngâm trong nước quá lâu vì dễ bị nứt, mốc.</p>',
    image_url: 'https://images.unsplash.com/photo-1596647262274-0f2d72561939?w=800&auto=format&fit=crop',
    category_name: 'Mẹo Vặt',
    author_name: 'Vợ Đảm',
    likes: 852,
    created_at: new Date(Date.now() - 86400000 * 22).toISOString(),
    status: 'approved'
  },
  {
    id: -8,
    title: 'Tại Sao Cần Uống Đủ Nước Khi Ăn Kiêng Keto?',
    excerpt: 'Chế độ Keto khiến bạn giảm cân nhanh nhưng cũng dễ dẫn đến mất nước và hụt khoáng chất. Giải pháp là gì?',
    content: '<p>Khi ăn Keto, việc cắt giảm Carbs khiến cơ thể cạn kiệt lượng glycogen dự trữ, từ đó làm mất đi lượng lớn nước và khoáng chất liên kết. Điều này gây ra hội chứng "Keto flu" (Cúm Keto). Uống ít nhất 2.5 - 3 lít nước mỗi ngày và bổ sung điện giải (muối hồng, kali, magie) là điều tối cần thiết.</p>',
    image_url: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800&auto=format&fit=crop',
    category_name: 'Dinh Dưỡng',
    author_name: 'Dr. Wellness',
    likes: 310,
    created_at: new Date(Date.now() - 86400000 * 25).toISOString(),
    status: 'approved'
  },
  {
    id: -9,
    title: 'Top 4 Quán Bún Bò Huế Cay Xé Lưỡi Tại Sài Gòn',
    excerpt: 'Team mê đồ cay chắc chắn không thể bỏ qua danh sách những quán bún bò chuẩn vị Huế, sa tế cay nồng nàn này.',
    content: '<p>1. Bún bò Nam Giao - Nổi tiếng với nước dùng đậm vị ruốc và sả. 2. Bún bò Hạnh - Đặc trưng với khoanh giò heo siêu to và chả cua dai giòn. 3. Bún bò O Vui - Chuyên trị những cái bụng đói đêm khuya. 4. Bún bò Chú Há - Mức độ cay tùy chọn nhưng sa tế ở đây thực sự là thử thách với nhiều người.</p>',
    image_url: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&auto=format&fit=crop',
    category_name: 'Review Nhà Hàng',
    author_name: 'SaiGon Eater',
    likes: 670,
    created_at: new Date(Date.now() - 86400000 * 28).toISOString(),
    status: 'approved'
  },
  {
    id: -10,
    title: 'Sự Khác Biệt Giữa Ẩm Thực Miền Bắc và Miền Tây',
    excerpt: 'Từ vị thanh tao, chua nhẹ của miền Bắc đến vị ngọt đậm đà, hào sảng của miền Tây Nam Bộ.',
    content: '<p>Ẩm thực miền Bắc thiên về hương vị thanh nhã, vừa phải, chuộng chua thanh từ mẻ, sấu. Các món ăn có phần cầu kỳ trong cách trình bày (như bún thang, phở). Ngược lại, ẩm thực miền Tây mang đậm tính phóng khoáng, vị ngọt thường nổi bật (do dùng nhiều đường, nước dừa), và sử dụng đa dạng các loại rau rừng, thủy sản đồng quê.</p>',
    image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop',
    category_name: 'Văn Hóa Ẩm Thực',
    author_name: 'Khám Phá VN',
    likes: 911,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
    status: 'approved'
  }
];
